name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "release"
  cancel-in-progress: true

env:
  TAG_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: ${{ github.event.repository.name }}
  AZURE_WEBAPP_PACKAGE_PATH: published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Build and Publish for Linux
      run: |
        dotnet publish ${{ env.WORKING_DIRECTORY }} \
        -c ${{ env.CONFIGURATION }} \
        -o "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/linux-x64/${{ env.WORKING_DIRECTORY }}" \
        -r linux-x64 \
        --no-self-contained \
        -p:PublishSingleFile=true \
        -p:DebugType=None
    - name: Create ZIP Archive for Linux
      run: |
        cd "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/linux-x64"
        zip -r "../${{ env.WORKING_DIRECTORY }}_linux-x64.zip" "${{ env.WORKING_DIRECTORY }}"

    - name: Build and Publish for Windows
      run: |
        dotnet publish ${{ env.WORKING_DIRECTORY }} \
        -c ${{ env.CONFIGURATION }} \
        -o "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/win-x64/${{ env.WORKING_DIRECTORY }}" \
        -r win-x64 \
        --no-self-contained \
        -p:PublishSingleFile=true \
        -p:DebugType=None
    - name: Create ZIP Archive for Windows
      run: |
        cd "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/win-x64"
        zip -r "../${{ env.WORKING_DIRECTORY }}_win-x64.zip" "${{ env.WORKING_DIRECTORY }}"

    - name: Configure Git
      run: |
        git config --local user.email "${{ github.event.pusher.email }}"
        git config --local user.name "${{ github.event.pusher.name }}"

    - name: Git Tag
      run: |
        git tag -f ${{ env.TAG_VERSION }}
        git push origin ${{ env.TAG_VERSION }} -f

    - uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.WORKING_DIRECTORY }}_linux-x64.zip
          ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.WORKING_DIRECTORY }}_win-x64.zip
        tag_name: ${{ env.TAG_VERSION }}
